AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Description: AWS Environment
    AllowedValues:
      - dev
      - prod
      - stage

  BranchName:
    Type: String
    Description: Version Control Branch Name

Resources:
  MedicalPeekStaticFilesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${Environment}.${BranchName}.medical-peek.callahanwilliam
      WebsiteConfiguration:
        IndexDocument: index.html

  MedicalPeedCloudFrontDistrobution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MedicalPeekStaticFilesBucket.DomainName
            Id: !Ref MedicalPeekStaticFilesBucket
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: !Ref MedicalPeekStaticFilesBucket
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

  MedicalPeekStaticFilesBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MedicalPeekStaticFilesBucket
      PolicyDocument:
        Statement:
          - Sid: ReadAccess
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub
              - "${BucketArn}/*"
              - BucketArn: !GetAtt MedicalPeekStaticFilesBucket.Arn
            Principal: "*"

#  MedicalPeekRoute53:
#    Type: 'AWS::Route53::RecordSet'
#    Properties:
#      AliasTarget:
#        HostedZoneName:
#        Name: !Sub ${Environment}.${BranchName}.medical-peek.callahanwilliam
#        Type: A
#        HostedZoneId: Z2FDTNDATAQYW2

