# Generated by Django 3.1.4 on 2021-01-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtractor',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('title', models.CharField(max_length=1024)),
                ('group_uuid', models.UUIDField()),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('mime_type', models.CharField(default='text/plain', max_length=50)),
                ('file_name', models.CharField(default='unnamed_file', max_length=255)),
            ],
            options={
                'db_table': 'file_extractor',
            },
        ),
    ]
