# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_peek_api', '0002_auto_20200411_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtractor',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('title', models.CharField(max_length=1024)),
                ('group_uuid', models.UUIDField()),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('mime_type', models.CharField(default='text/plain', max_length=50)),
                ('file_name', models.CharField(default='unnamed_file', max_length=255)),
                ('category', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('nomenclature', models.CharField(blank=True, max_length=4096, null=True)),
                ('description', models.TextField(null=True)),
                ('nsn', models.IntegerField(max_length=13, null=True)),
                ('msn', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'medical_item',
            },
        ),
        migrations.CreateModel(
            name='MedicalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('link', models.CharField(max_length=4096, null=True)),
            ],
            options={
                'db_table': 'medical_resource',
            },
        ),
        migrations.AddField(
            model_name='medicalitem',
            name='medical_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medical_peek_api.MedicalResource'),
        ),
    ]
