# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_peek_api', '0003_auto_20200411_1028'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileextractor',
            table='file_extractor',
        ),
    ]
