# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_peek_api', '0004_auto_20200411_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileextractor',
            name='category',
        ),
    ]
