# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_peek_api', '0005_remove_fileextractor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalitem',
            name='medical_resource',
        ),
        migrations.DeleteModel(
            name='MedicalItem',
        ),
        migrations.DeleteModel(
            name='MedicalResource',
        ),
    ]
