# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_peek_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalresource',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
