AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AccountName:
    Description: Name of the account
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /dev/account-name

  Environment:
    Type: String
    Description: AWS Environment
    AllowedValues:
      - dev
      - prod
      - stage

  BranchName:
    Type: String
    Description: Version Control Branch Name

  CertificateArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: SSL Certificate to use for the Medical Peek Api
    Default: /dev/callahanwilliam/wildcard-certificate

Resources:
  MedicalPeekStaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}.${BranchName}.medical-peek-web.${AccountName}
      WebsiteConfiguration:
        IndexDocument: index.html
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'

  MedicalPeedCloudFrontDistrobution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${Environment}-${BranchName}-medical-peek-web.${AccountName}.com
        Origins:
          - DomainName: !GetAtt MedicalPeekStaticFilesBucket.DomainName
            Id: !Ref MedicalPeekStaticFilesBucket
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: !Ref MedicalPeekStaticFilesBucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018

  MedicalPeekStaticFilesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MedicalPeekStaticFilesBucket
      PolicyDocument:
        Statement:
          - Sid: ReadAccess
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub
              - '${BucketArn}/*'
              - BucketArn: !GetAtt MedicalPeekStaticFilesBucket.Arn
            Principal: '*'

  MedicalPeekRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt MedicalPeedCloudFrontDistrobution.DomainName
      HostedZoneId: Z31CWL47Z21FZC
      Name: !Sub ${Environment}-${BranchName}-medical-peek-web.${AccountName}.com.
      Type: A
